sudo: required
dist: trusty # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109

install:
  # LDTP
  - sudo apt-get install python-twisted-web
  - sudo apt-get install python-wnck
  #- sudo apt-get install python-gnome
  # Documentation
  #- sudo apt-get install rst2pdf

script:
  # Build LDTP
  - python setup.py build
  - sudo python setup.py install
  # Build documentation
  # Build and run examples